DB_NAME = 'postgres'
DB_USER = 'postgres'
DB_PASS = 'postgres'
DB_HOST = 'localhost'
DB_PORT = 5432

SENSOR_ID = 0
SENSOR_NAME = 1
SENSOR_LOCATION = 2

SENSORVAL_ID = 0
SENSORVAL_VALUE = 1
SENSORVAL_SENSOR = 2
SENSORVAL_DATE = 3